service: ts-wetter-api

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}

functions:
  getTemp:
    handler: handler.getTemp
    events:
      - http:
          path: wetter
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                paramName: true
